export const routes = {
  login: "/login",
  dashboard: "/dashboard",
  scheduler: "/scheduler",
  inbox: "/inbox",
  team: "/team",
  history: "/history",
  reports: "/reports",
  notifications: "/notifications",
  profile: "/profile",
  availability: "/availability",
  checkIn: "/checkin",
  attendanceHistory: "/attendance-history",
  attendanceMonitor: "/attendance-monitor",
  weekAssignments: "/week-assignments",
};
